### ISSUE TITLE
World Boarder Resetting on Server Reload

### ISSUE THREAD

**Issue by BakProject** [Brettflan/WorldBorder#110]
I am using the World Border plugin on my server, and it was working just fine! And then out of the blue the border just starts to reset back to default config . I deleted the config to 'reload' the config because maybe the config changed? It did not. 

I am now getting an internal error message when I even try to set the border with the 'reloaded' config.

![2018-09-28_11 23 35](https://user-images.githubusercontent.com/34917462/46220844-075a0300-c311-11e8-8084-d06e8510f072.png)

The command under the chat box is the command I typed.

Config file:

cfg-version: 11
message: '&cYou have reached the edge of this world.'
round-border: true
debug-mode: false
whoosh-effect: true
portal-redirection: true
knock-back-dist: 1.0
timer-delay-ticks: 5
remount-delay-ticks: 0
dynmap-border-enabled: true
dynmap-border-message: The border of the world.
player-killed-bad-spawn: false
deny-enderpearl: true
fill-autosave-frequency: 30
bypass-list-uuids:
-- 939258e6-b7c8-40b2-8778-854ddbab986b
fill-memory-tolerance: 500
prevent-block-place: true
prevent-mob-spawn: true
dynmap-border-hideByDefault: false
dynmap-border-priority: 0

The ' -- ' next to the UUID is really only one ' - '

**Comment by Brettflan** [comment]
That's definitely not normal, and I haven't heard of this error before. What version of Spigot are you using, and what version of WorldBorder (are they listed as compatible)? Can you post the server log from when you got that "internal error"?

**Comment by BakProject** [comment]
[15:30:37] [Server thread/INFO]: blazex224 issued server command: /wb set 17500 17500
[15:30:37] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'wb' in plugin WorldBorder v1.9.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot121.jar:git-Spigot-edd0396-2a927e8]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot121.jar:git-Spigot-edd0396-2a927e8]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot121.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1386) [spigot121.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1221) [spigot121.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot121.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot121.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot121.jar:git-Spigot-edd0396-2a927e8]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot121.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot121.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot121.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot121.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot121.jar:git-Spigot-edd0396-2a927e8]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.wimbli.WorldBorder.BorderData
	at com.wimbli.WorldBorder.Config.setBorder(Config.java:95) ~[?:?]
	at com.wimbli.WorldBorder.cmd.CmdSet.execute(CmdSet.java:142) ~[?:?]
	at com.wimbli.WorldBorder.WBCommand.onCommand(WBCommand.java:141) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot121.jar:git-Spigot-edd0396-2a927e8]
	... 15 more

**Comment by BakProject** [comment]
[latest.log](https://github.com/Brettflan/WorldBorder/files/2429477/latest.log)

**Comment by Brettflan** [comment]
You are running WorldBorder 1.9.0 on Spigot 1.12. WB 1.9.0 is only compatible with Spigot 1.13+.

For older versions:

https://dev.bukkit.org/projects/worldborder
