### ISSUE TITLE
Fill pause

### ISSUE THREAD

**Issue by Misio12320** [Brettflan/WorldBorder#125]
4 more chunks processed (355219 total, ~22.6%) (free mem: 534 MB)
> [22:07:33 WARN]: [WorldBorder] Task #4 for WorldBorder v1.9.0 generated an exception
net.minecraft.server.v1_13_R2.ReportedException: Exception generating new chunk
at net.minecraft.server.v1_13_R2.ChunkProviderServer.a(ChunkProviderServer.java:169) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
at net.minecraft.server.v1_13_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:114) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
at org.bukkit.craftbukkit.v1_13_R2.CraftWorld.loadChunk(CraftWorld.java:274) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
at com.wimbli.WorldBorder.WorldFillTask.run(WorldFillTask.java:203) ~[?:?]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:391) [spigot.jar:git-Spigot-518206a-a5b9c7b]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:888) [spigot.jar:git-Spigot-518206a-a5b9c7b]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-518206a-a5b9c7b]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:830) [spigot.jar:git-Spigot-518206a-a5b9c7b]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:728) [spigot.jar:git-Spigot-518206a-a5b9c7b]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: java.util.concurrent.CompletionException: java.lang.OutOfMemoryError: GC overhead limit exceeded
at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_202]
at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_202]
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592) ~[?:1.8.0_202]
at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:260) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
at java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1604) ~[?:1.8.0_202]
at java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:1830) ~[?:1.8.0_202]
at net.minecraft.server.v1_13_R2.Scheduler.a(SourceFile:62) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
at net.minecraft.server.v1_13_R2.SchedulerBatch.a(SourceFile:39) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
at net.minecraft.server.v1_13_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:109) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
... 9 more
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
at net.minecraft.server.v1_13_R2.DataPaletteLinear.<init>(SourceFile:22) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
at net.minecraft.server.v1_13_R2.DataPaletteBlock.b(SourceFile:77) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
at net.minecraft.server.v1_13_R2.DataPaletteBlock.<init>(SourceFile:61) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
at net.minecraft.server.v1_13_R2.ChunkSection.<init>(SourceFile:26) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
at net.minecraft.server.v1_13_R2.ChunkRegionLoader.a(ChunkRegionLoader.java:838) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
at net.minecraft.server.v1_13_R2.ChunkRegionLoader.a(ChunkRegionLoader.java:622) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
at net.minecraft.server.v1_13_R2.ChunkRegionLoader.a(ChunkRegionLoader.java:211) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
at net.minecraft.server.v1_13_R2.ChunkRegionLoader.b(ChunkRegionLoader.java:253) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
at net.minecraft.server.v1_13_R2.ChunkRegionLoader.b(ChunkRegionLoader.java:187) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
at net.minecraft.server.v1_13_R2.ChunkTaskScheduler.lambda$2(ChunkTaskScheduler.java:55) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
at net.minecraft.server.v1_13_R2.ChunkTaskScheduler$$Lambda$1779/1143781143.apply(Unknown Source) ~[?:?]
at org.bukkit.craftbukkit.libs.it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.computeIfAbsent(Long2ObjectOpenHashMap.java:479) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
at net.minecraft.server.v1_13_R2.ExpiringMap.computeIfAbsent(ExpiringMap.java:86) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
at net.minecraft.server.v1_13_R2.ChunkTaskScheduler.a(ChunkTaskScheduler.java:51) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
at net.minecraft.server.v1_13_R2.ChunkTaskScheduler.a(ChunkTaskScheduler.java:1) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
at net.minecraft.server.v1_13_R2.Scheduler.b(SourceFile:80) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
at net.minecraft.server.v1_13_R2.Scheduler$a$$Lambda$1788/8734782.accept(Unknown Source) ~[?:?]
at net.minecraft.server.v1_13_R2.ChunkStatus$1.a(SourceFile:46) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
at net.minecraft.server.v1_13_R2.ChunkStatus$1.a(SourceFile:27) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
at net.minecraft.server.v1_13_R2.Scheduler$a$$Lambda$1787/832025292.apply(Unknown Source) ~[?:?]
at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_202]
at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
at net.minecraft.server.v1_13_R2.Scheduler$a$$Lambda$1788/8734782.accept(Unknown Source) ~[?:?]
at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
at net.minecraft.server.v1_13_R2.Scheduler$a$$Lambda$1787/832025292.apply(Unknown Source) ~[?:?]
at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_202]
at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
>Tp
> [09:02:01 INFO]: Unknown command
> [09:02:01 INFO]: /tp<--[HERE]
>Wb fill pause
> [09:02:09 INFO]: [WorldBorder] [Fill] 8 more chunks processed (355227 total, ~22.6%) (free mem: 1337 MB)
> [09:02:09 INFO]: [WorldBorder] [Fill] Saving the world to disk, just to be on the safe side. (free mem: 1337 MB)
> [09:02:09 INFO]: The world map generation task is now paused.
>Wb fill pause
> [09:02:16 INFO]: The world map generation task is now unpaused.
>Wb reload
> [09:02:22 INFO]: [WorldBorder] [CONFIG] Using elliptic/round border, knockback of 3.0 blocks, and timer delay of 5.
> [09:02:22 INFO]: [WorldBorder] [CONFIG] Border-checking timed task started.
> [09:02:22 INFO]: [WorldBorder] [CONFIG] World "world" has border radius 10000 at X: 245.7 Z: -203.5
> [09:02:22 INFO]: [WorldBorder] [CONFIG] Configuration loaded.
>Tps
> [09:02:34 INFO]: TPS from last 1m, 5m, 15m: 19.98, 19.98, 19.98
>Wb fill pause
> [09:02:39 INFO]: [WorldBorder] [Fill] 0 more chunks processed (355227 total, ~22.6%) (free mem: 1296 MB)
> [09:02:39 INFO]: [WorldBorder] [Fill] Saving the world to disk, just to be on the safe side. (free mem: 1296 MB)
> [09:02:39 INFO]: The world map generation task is now paused.
>Wb fill pause
> [09:02:43 INFO]: The world map generation task is now unpaused.
Hello again. When I fill my world executing command wb fill 400 400 true it fills some % and stops. version WB 1.9.0 This server is running CraftBukkit version git-Spigot-518206a-a5b9c7b (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by Cookietank** [comment]
I'm having the same issue, how did you fix it?

**Comment by Misio12320** [comment]
Might out of RAM and just crashed
