### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by YourCoalAlt** [Brettflan/WorldBorder#142]
when running /wb fill with default settings, it will run for a minute or so but eventually comes with this error:

`[18:14:32] [Server thread/WARN]: [WorldBorder] Task #18 for WorldBorder v1.9.10 (beta) generated an exception
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1490) ~[?:?]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1513) ~[?:?]
	at java.lang.Iterable.forEach(Iterable.java:74) ~[?:?]
	at net.minecraft.server.v1_14_R1.ChunkMapDistance.a(SourceFile:132) ~[spigot-1.14.2-R0.1-SNAPSHOT.jar:git-Spigot-df0eb25-9e95da1]
	at net.minecraft.server.v1_14_R1.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:204) ~[spigot-1.14.2-R0.1-SNAPSHOT.jar:git-Spigot-df0eb25-9e95da1]
	at net.minecraft.server.v1_14_R1.ChunkProviderServer.getChunkFutureMainThread(ChunkProviderServer.java:144) ~[spigot-1.14.2-R0.1-SNAPSHOT.jar:git-Spigot-df0eb25-9e95da1]
	at net.minecraft.server.v1_14_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:91) ~[spigot-1.14.2-R0.1-SNAPSHOT.jar:git-Spigot-df0eb25-9e95da1]
	at net.minecraft.server.v1_14_R1.World.getChunkAt(World.java:212) ~[spigot-1.14.2-R0.1-SNAPSHOT.jar:git-Spigot-df0eb25-9e95da1]
	at net.minecraft.server.v1_14_R1.IWorldReader.getChunkAt(SourceFile:105) ~[spigot-1.14.2-R0.1-SNAPSHOT.jar:git-Spigot-df0eb25-9e95da1]
	at net.minecraft.server.v1_14_R1.World.getChunkAt(World.java:207) ~[spigot-1.14.2-R0.1-SNAPSHOT.jar:git-Spigot-df0eb25-9e95da1]
	at net.minecraft.server.v1_14_R1.WorldServer.setForceLoaded(WorldServer.java:1444) ~[spigot-1.14.2-R0.1-SNAPSHOT.jar:git-Spigot-df0eb25-9e95da1]
	at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.setChunkForceLoaded(CraftWorld.java:485) ~[spigot-1.14.2-R0.1-SNAPSHOT.jar:git-Spigot-df0eb25-9e95da1]
	at com.wimbli.WorldBorder.WorldFillTask.run(WorldFillTask.java:318) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.2-R0.1-SNAPSHOT.jar:git-Spigot-df0eb25-9e95da1]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.14.2-R0.1-SNAPSHOT.jar:git-Spigot-df0eb25-9e95da1]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1008) [spigot-1.14.2-R0.1-SNAPSHOT.jar:git-Spigot-df0eb25-9e95da1]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot-1.14.2-R0.1-SNAPSHOT.jar:git-Spigot-df0eb25-9e95da1]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956) [spigot-1.14.2-R0.1-SNAPSHOT.jar:git-Spigot-df0eb25-9e95da1]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801) [spigot-1.14.2-R0.1-SNAPSHOT.jar:git-Spigot-df0eb25-9e95da1]
	at java.lang.Thread.run(Thread.java:825) [?:?]`

**Comment by Brettflan** [comment]
The problem is in Spigot (or possibly Paper).

**Comment by robotnikthingy** [comment]
getting the same error on 1.14.3 spigot
