### ISSUE TITLE
Error after /wb bypasslist

### ISSUE THREAD

**Issue by Nety01** [Brettflan/WorldBorder#157]
Hi, I'm getting this error in command /wb bypasslist

` [16:57:05 WARN]: java.lang.NullPointerException
[16:57:05 WARN]: at com.wimbli.WorldBorder.UUID.UUIDFetcher.getName(UUIDFetcher.java:128)
[16:57:05 WARN]: at com.wimbli.WorldBorder.UUID.UUIDFetcher.getNameList(UUIDFetcher.java:145)
[16:57:05 WARN]: at com.wimbli.WorldBorder.cmd.CmdBypasslist$1.run(CmdBypasslist.java:45)
[16:57:05 WARN]: at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84)
[16:57:05 WARN]: at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449)
[16:57:05 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1010)
[16:57:05 WARN]: at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[16:57:05 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940)
[16:57:05 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837)
[16:57:05 WARN]: at java.lang.Thread.run(Thread.java:745)`

And instead of my name I see "null".

**Comment by Brettflan** [comment]
The bypass list is stored as a list of player UUIDs, since player names can be changed while UUIDs are the unique account ID which never changes. When it needs to check the player name associated with a given UUID (done once per server start and then cached), it checks that with the Mojang server.

The error you're getting is with it trying to check the stored UUID with Mojang's server for the associated player name.

You might try "/wb bypass null off" to try to remove that bypass, then "/wb bypass [your_player_name] on" to add yourself back to the bypass list. Then restart the server and run "/wb bypasslist" again to see if that fixed it.

If the problem persists, could you provide me with your player name so I can test it? I've just re-tested with my player name and another and couldn't find any problem.

**Comment by Nety01** [comment]
Well, "/wb bypass null off" doesn't remove the null from bypass list. But from what you said, it could be because the not working username is not premium version of minecraft and the server is in offline-mode?

**Comment by Brettflan** [comment]
Well yeah, an old (now unsupported by Mojang) demo-mode account will not work.
