### ISSUE TITLE
Issues with map render on 1.15.2

### ISSUE THREAD

**Issue by Nikox3003** [Brettflan/WorldBorder#174]
Hi, i wanted to increase the world size and pre-render it. However, it stops there:
```
[19:11:53 INFO]: [WorldBorder] [Fill] 25856 more chunks processed (1546752 total, ~42.7%) (free mem: 485 MB)
[19:11:58 INFO]: [WorldBorder] [Fill] 25856 more chunks processed (1572608 total, ~43.4%) (free mem: 357 MB)
[19:12:03 INFO]: [WorldBorder] [Fill] 25856 more chunks processed (1598464 total, ~44.1%) (free mem: 231 MB)
[19:12:06 WARN]: [WorldBorder] Task #2208100 for WorldBorder v1.9.10 (beta) generated an exception
java.lang.NoClassDefFoundError: io/papermc/lib/PaperLib
        at com.wimbli.WorldBorder.WorldFillTask.run(WorldFillTask.java:319) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-85]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.2.jar:git-Paper-85]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185) ~[patched_1.15.2.jar:git-Paper-85]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-85]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-85]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-85]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: io.papermc.lib.PaperLib
        at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.15.2.jar:git-Paper-85]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.15.2.jar:git-Paper-85]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        ... 8 more
```
After a restart or pause & unpause, still won't work.

I'm not sure if it's issue with paper or the plugin, but will post first here.
Server version: **git-Paper-85 (MC: 1.15.2)**
Plugin version: **1.9.10 (beta)**

**Comment by Nikox3003** [comment]
After some analysis, I noticed that I'm using fork. I didn't notice it earlier, beacause `/ver WorldBorder` was the same as the original and I forgot that I'm even using it. Sorry.
