### ISSUE TITLE
1.7.9 spigot worldborder error

### ISSUE THREAD

**Issue by bartonsweb** [Brettflan/WorldBorder#62]
21.04 12:44:16 [Server] WARN [WorldBorder] Task #5 for WorldBorder v1.8.1 generated an exception
21.04 12:44:16 [Server] INFO java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
21.04 12:44:16 [Server] INFO at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_77]
21.04 12:44:16 [Server] INFO at java.util.ArrayList.set(ArrayList.java:444) ~[?:1.8.0_77]
21.04 12:44:16 [Server] INFO at net.minecraft.server.v1_7_R4.RegionFile.<init>(RegionFile.java:66) ~[spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
21.04 12:44:16 [Server] INFO at net.minecraft.server.v1_7_R4.RegionFileCache.a(RegionFileCache.java:31) ~[spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
21.04 12:44:16 [Server] INFO at net.minecraft.server.v1_7_R4.ChunkRegionLoader.chunkExists(ChunkRegionLoader.java:41) ~[spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
21.04 12:44:16 [Server] INFO at net.minecraft.server.v1_7_R4.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:115) ~[spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
21.04 12:44:16 [Server] INFO at net.minecraft.server.v1_7_R4.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:102) ~[spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
21.04 12:44:16 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.CraftWorld.loadChunk(CraftWorld.java:248) ~[spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
21.04 12:44:16 [Server] INFO at com.wimbli.WorldBorder.WorldFillTask.run(WorldFillTask.java:198) ~[?:?]
21.04 12:44:16 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
21.04 12:44:16 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
21.04 12:44:16 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:641) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
21.04 12:44:16 [Server] INFO at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
21.04 12:44:16 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
21.04 12:44:16 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
21.04 12:44:16 [Server] INFO at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]

Everytime the world fill reaches 55-58% complete this error happens and it stops, restarting server starts the fill from 30-40% again.

**Comment by bartonsweb** [comment]
I fixed this by manually deleting all of the region files that were under 8kb in size (The average is 1000kb-4000kb) and it seems to be working, I will close issue but this is here as a note :)
